### ISSUE TITLE
Error with ?setup

### ISSUE THREAD

**Issue by Corentin-rouff** [MattBSG/RSVP-Bot#1]
Ignoring exception in on_command_error
Traceback (most recent call last):
  File "/home/container/discord/ext/commands/core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "/home/container/modules/main.py", line 401, in _setup
    if ctx.author.id not in [app_info.owner.id, ctx.guild.owner.id]:
AttributeError: 'NoneType' object has no attribute 'id'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/container/discord/client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "/home/container/bot.py", line 59, in on_command_error
    raise error
  File "/home/container/discord/ext/commands/bot.py", line 902, in invoke
    await ctx.command.invoke(ctx)
  File "/home/container/discord/ext/commands/core.py", line 864, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "/home/container/discord/ext/commands/core.py", line 94, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: AttributeError: 'NoneType' object has no attribute 'id'

I did realize what you wrote in readme ... please help me

**Comment by MattBSG** [comment]
Hi, is your bot application owned on a developer team on discord.com/developers ?

**Comment by Corentin-rouff** [comment]
[https://prnt.sc/10z6xwa](url)
Yes, maybe error with settings ?

**Comment by Corentin-rouff** [comment]
Hey, find problems : main.py line 400
I deleted these lines of code and it works : 

        app_info = await self.bot.application_info()
        if ctx.author.id not in [app_info.owner.id, ctx.guild.owner.id]:
            return await ctx.send(f'{ctx.author.mention} You must be the owner of this server or bot to use this command')
